pipeline{
    agent{
        docker{ 
            image 'python:2.7.16-alpine' 
            args '-v $HOME/.m2:/root/.m2 --user root'
        }
    }
    stages{
        stage('Build'){
            when{
                changeset '**/vote/**'
            }
            steps{
                echo 'Running build vote app'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('Test'){
            when{
                changeset '**/vote/**'
            }
            steps{
                echo 'Running tests vote app'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                    sh 'nosetests -v'
                }
            }
        }
    }
    post{
        always{
            echo 'Vote app pipeline completed'
        }
        success{
            slackSend(message: "Build Succedeed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        failure{
            slackSend(message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
} 
