pipeline {
    agent any
    
    tools {
        maven 'mvn 3.6'
    } 

    stages {
        stage('build') {
            steps {
                echo 'Compiling worker app'
		        dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            steps {
                echo 'Running tests'
		        dir('worker'){
                    sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            steps {
                echo 'Creating packages'
		        dir('worker'){
                    sh 'mvn package'
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true

            echo 'Worker pipeline execution completed'
        }
    }
}

