pipeline {
    agent any
    
    tools {
        maven 'mvn 3.6'
    } 

    stages {
        stage('build') {
            slackSend "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
            when{
                changeset "**/worker/**"
            }
            steps {
                echo 'Compiling worker app'
		        dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            when{
                changeset "**/worker/**"
            }
            steps {
                echo 'Running tests'
		        dir('worker'){
                    sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            when{
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'Creating packages'
		        dir('worker'){
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }
    post {
        always {
            echo 'Worker pipeline execution completed'
        }
        failure {
            slackSend "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"

        }
        success {
            slackSend "Build Succedeed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"

        }
    }
}

